import WebSocketComponent from "@/components/WebSocketTest"

const General = () => {
  return (
    <div>   
      {/* <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. In a natus veritatis commodi culpa! Debitis, molestiae tenetur! Ex repudiandae iusto cupiditate libero reiciendis eum non alias ducimus, accusamus praesentium facilis facere asperiores, beatae exercitationem veniam minus fugit unde ullam, et recusandae. Ab velit magnam quo necessitatibus ducimus aliquam, sed sint eveniet consectetur iure. Eveniet perspiciatis a voluptatum accusantium deleniti doloribus doloremque iusto reiciendis cum culpa hic nihil sunt, quos odit mollitia nam vitae corrupti facere vero perferendis distinctio odio veniam repellendus? Officiis perferendis, laboriosam laborum itaque aut reprehenderit voluptate molestias autem quia! Sunt, facere! Atque excepturi laborum aut consectetur nihil provident vero iure temporibus dolorem non aliquam blanditiis illum, saepe deserunt nobis ipsam, ullam accusamus. Voluptates veritatis saepe beatae iure rem neque commodi voluptate, adipisci numquam dignissimos placeat ad obcaecati autem similique nisi perferendis sit quidem. Doloremque voluptatibus dolor minus ducimus quam voluptate! Accusantium tempora esse alias id. Earum reiciendis neque quo possimus odio aliquid consequatur expedita esse, veniam distinctio ratione exercitationem nesciunt suscipit velit modi optio doloremque assumenda nihil! Autem, accusantium magni consequatur delectus provident placeat illum. Qui repellendus reiciendis possimus, doloribus et alias! Veniam eum laudantium ipsam inventore velit adipisci debitis dolorem aperiam vero dolor autem est deserunt quibusdam, sint eligendi sed nostrum tempora omnis? Magnam quia ullam laboriosam, repellat neque ea, velit eaque praesentium repudiandae iste, delectus adipisci! Optio ipsum obcaecati officiis deleniti error sapiente pariatur in delectus velit, modi omnis dolorum saepe eligendi praesentium fugiat harum vero aspernatur porro. Laboriosam harum beatae omnis veritatis iste dolorum quasi. Totam vitae ipsa ea? Perspiciatis ipsam, quas quia hic dicta, laborum itaque cum at explicabo provident asperiores quae quasi dolor dolores inventore natus. Enim iusto repudiandae corrupti accusantium facere est, inventore aliquam nesciunt praesentium adipisci, deserunt ipsum accusamus. Facere, magni. Blanditiis doloremque voluptatibus architecto, officiis error dolore fugit provident.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. In a natus veritatis commodi culpa! Debitis, molestiae tenetur! Ex repudiandae iusto cupiditate libero reiciendis eum non alias ducimus, accusamus praesentium facilis facere asperiores, beatae exercitationem veniam minus fugit unde ullam, et recusandae. Ab velit magnam quo necessitatibus ducimus aliquam, sed sint eveniet consectetur iure. Eveniet perspiciatis a voluptatum accusantium deleniti doloribus doloremque iusto reiciendis cum culpa hic nihil sunt, quos odit mollitia nam vitae corrupti facere vero perferendis distinctio odio veniam repellendus? Officiis perferendis, laboriosam laborum itaque aut reprehenderit voluptate molestias autem quia! Sunt, facere! Atque excepturi laborum aut consectetur nihil provident vero iure temporibus dolorem non aliquam blanditiis illum, saepe deserunt nobis ipsam, ullam accusamus. Voluptates veritatis saepe beatae iure rem neque commodi voluptate, adipisci numquam dignissimos placeat ad obcaecati autem similique nisi perferendis sit quidem. Doloremque voluptatibus dolor minus ducimus quam voluptate! Accusantium tempora esse alias id. Earum reiciendis neque quo possimus odio aliquid consequatur expedita esse, veniam distinctio ratione exercitationem nesciunt suscipit velit modi optio doloremque assumenda nihil! Autem, accusantium magni consequatur delectus provident placeat illum. Qui repellendus reiciendis possimus, doloribus et alias! Veniam eum laudantium ipsam inventore velit adipisci debitis dolorem aperiam vero dolor autem est deserunt quibusdam, sint eligendi sed nostrum tempora omnis? Magnam quia ullam laboriosam, repellat neque ea, velit eaque praesentium repudiandae iste, delectus adipisci! Optio ipsum obcaecati officiis deleniti error sapiente pariatur in delectus velit, modi omnis dolorum saepe eligendi praesentium fugiat harum vero aspernatur porro. Laboriosam harum beatae omnis veritatis iste dolorum quasi. Totam vitae ipsa ea? Perspiciatis ipsam, quas quia hic dicta, laborum itaque cum at explicabo provident asperiores quae quasi dolor dolores inventore natus. Enim iusto repudiandae corrupti accusantium facere est, inventore aliquam nesciunt praesentium adipisci, deserunt ipsum accusamus. Facere, magni. Blanditiis doloremque voluptatibus architecto, officiis error dolore fugit provident.</p> */}

      <WebSocketComponent/>
    </div>
  )
}

export default General